access-control.name=opa
opa.policy.uri=http://opa:8181/v1/data/trino/allow
opa.policy.row-filters-uri=http://opa:8181/v1/data/trino/row_filters
opa.policy.column-masks-uri=http://opa:8181/v1/data/trino/column_masks
